// Alle Fahrzeugtypen des Leitstellenspiels mit ihrer festen Typ-ID (vehicle_type_id).
// Die ID ändert sich nie – auch nicht, wenn du Fahrzeuge oder Typen im Spiel umbenennst.
// Quelle: LSS-Manager (de_DE), Stand Oktober 2026. Gruppe nach Wachentyp.
const LSS_VEHICLE_TYPES = [
  [0, "LF 20", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [1, "LF 10", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [6, "LF 8/6", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [7, "LF 20/16", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [8, "LF 10/6", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [9, "LF 16-TS", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [17, "TLF 2000", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [18, "TLF 3000", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [19, "TLF 8/8", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [20, "TLF 8/18", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [21, "TLF 16/24-Tr", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [22, "TLF 16/25", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [23, "TLF 16/45", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [24, "TLF 20/40", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [25, "TLF 20/40-SL", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [26, "TLF 16", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [30, "HLF 20", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [37, "TSF-W", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [87, "TLF 4000", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [88, "KLF", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [89, "MLF", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [90, "HLF 10", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [107, "LF-L", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [121, "GTLF", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [163, "HLF Schiene", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [187, "TLF 3000 W", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [188, "TLF 5000 W", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [189, "GTLF 10000 W", "Feuerwehr – Lösch- und Tanklöschfahrzeuge"],
  [2, "DLK 23", "Feuerwehr – Sonderfahrzeuge"],
  [3, "ELW 1", "Feuerwehr – Sonderfahrzeuge"],
  [4, "RW", "Feuerwehr – Sonderfahrzeuge"],
  [5, "GW-A", "Feuerwehr – Sonderfahrzeuge"],
  [10, "GW-Öl", "Feuerwehr – Sonderfahrzeuge"],
  [11, "GW-L2-Wasser", "Feuerwehr – Sonderfahrzeuge"],
  [12, "GW-Messtechnik", "Feuerwehr – Sonderfahrzeuge"],
  [13, "SW 1000", "Feuerwehr – Sonderfahrzeuge"],
  [14, "SW 2000", "Feuerwehr – Sonderfahrzeuge"],
  [15, "SW 2000-Tr", "Feuerwehr – Sonderfahrzeuge"],
  [16, "SW Kats", "Feuerwehr – Sonderfahrzeuge"],
  [27, "GW-Gefahrgut", "Feuerwehr – Sonderfahrzeuge"],
  [33, "GW-Höhenrettung", "Feuerwehr – Sonderfahrzeuge"],
  [34, "ELW 2", "Feuerwehr – Sonderfahrzeuge"],
  [36, "MTW", "Feuerwehr – Sonderfahrzeuge"],
  [46, "WLF", "Feuerwehr – Sonderfahrzeuge"],
  [53, "Dekon-P", "Feuerwehr – Sonderfahrzeuge"],
  [57, "FwK", "Feuerwehr – Sonderfahrzeuge"],
  [75, "FLF", "Feuerwehr – Sonderfahrzeuge"],
  [76, "Rettungstreppe", "Feuerwehr – Sonderfahrzeuge"],
  [83, "GW-Werkfeuerwehr", "Feuerwehr – Sonderfahrzeuge"],
  [84, "ULF mit Löscharm", "Feuerwehr – Sonderfahrzeuge"],
  [85, "TM 50", "Feuerwehr – Sonderfahrzeuge"],
  [86, "Turbolöscher", "Feuerwehr – Sonderfahrzeuge"],
  [104, "GW-L1", "Feuerwehr – Sonderfahrzeuge"],
  [105, "GW-L2", "Feuerwehr – Sonderfahrzeuge"],
  [106, "MTF-L", "Feuerwehr – Sonderfahrzeuge"],
  [111, "NEA50", "Feuerwehr – Sonderfahrzeuge"],
  [113, "NEA200", "Feuerwehr – Sonderfahrzeuge"],
  [114, "GW-Lüfter", "Feuerwehr – Sonderfahrzeuge"],
  [118, "Kleintankwagen", "Feuerwehr – Sonderfahrzeuge"],
  [120, "Tankwagen", "Feuerwehr – Sonderfahrzeuge"],
  [126, "MTF Drohne", "Feuerwehr – Sonderfahrzeuge"],
  [128, "ELW Drohne", "Feuerwehr – Sonderfahrzeuge"],
  [129, "ELW2 Drohne", "Feuerwehr – Sonderfahrzeuge"],
  [138, "GW-Verpflegung", "Feuerwehr – Sonderfahrzeuge"],
  [139, "GW-Küche", "Feuerwehr – Sonderfahrzeuge"],
  [140, "MTW-Verpflegung", "Feuerwehr – Sonderfahrzeuge"],
  [141, "FKH", "Feuerwehr – Sonderfahrzeuge"],
  [162, "RW-Schiene", "Feuerwehr – Sonderfahrzeuge"],
  [166, "PTLF 4000", "Feuerwehr – Sonderfahrzeuge"],
  [167, "SLF", "Feuerwehr – Sonderfahrzeuge"],
  [185, "GW-Tierrettung", "Feuerwehr – Sonderfahrzeuge"],
  [190, "GW-Waldbrand", "Feuerwehr – Sonderfahrzeuge"],
  [47, "AB-Rüst", "Feuerwehr – Abrollbehälter / Anhänger"],
  [48, "AB-Atemschutz", "Feuerwehr – Abrollbehälter / Anhänger"],
  [49, "AB-Öl", "Feuerwehr – Abrollbehälter / Anhänger"],
  [54, "AB-Dekon-P", "Feuerwehr – Abrollbehälter / Anhänger"],
  [62, "AB-Schlauch", "Feuerwehr – Abrollbehälter / Anhänger"],
  [71, "AB-MZB", "Feuerwehr – Abrollbehälter / Anhänger"],
  [77, "AB-Gefahrgut", "Feuerwehr – Abrollbehälter / Anhänger"],
  [78, "AB-Einsatzleitung", "Feuerwehr – Abrollbehälter / Anhänger"],
  [108, "AB-L", "Feuerwehr – Abrollbehälter / Anhänger"],
  [115, "Anh Lüfter", "Feuerwehr – Abrollbehälter / Anhänger"],
  [116, "AB-Lüfter", "Feuerwehr – Abrollbehälter / Anhänger"],
  [117, "AB-Tank", "Feuerwehr – Abrollbehälter / Anhänger"],
  [119, "AB-Lösch", "Feuerwehr – Abrollbehälter / Anhänger"],
  [142, "AB-Küche", "Feuerwehr – Abrollbehälter / Anhänger"],
  [143, "Anh Schlauch", "Feuerwehr – Abrollbehälter / Anhänger"],
  [164, "AB-Schiene", "Feuerwehr – Abrollbehälter / Anhänger"],
  [168, "Anh Sonderlöschmittel", "Feuerwehr – Abrollbehälter / Anhänger"],
  [169, "AB-Sonderlöschmittel", "Feuerwehr – Abrollbehälter / Anhänger"],
  [170, "AB-Wasser/Schaum", "Feuerwehr – Abrollbehälter / Anhänger"],
  [179, "AB-NEA50", "Feuerwehr – Abrollbehälter / Anhänger"],
  [180, "AB-NEA200", "Feuerwehr – Abrollbehälter / Anhänger"],
  [186, "Anh Tierrettung", "Feuerwehr – Abrollbehälter / Anhänger"],
  [191, "Anh Waldbrand", "Feuerwehr – Abrollbehälter / Anhänger"],
  [192, "AB-Waldbrand", "Feuerwehr – Abrollbehälter / Anhänger"],
  [28, "RTW", "Rettungsdienst"],
  [29, "NEF", "Rettungsdienst"],
  [31, "RTH", "Rettungsdienst"],
  [38, "KTW", "Rettungsdienst"],
  [55, "KdoW-LNA", "Rettungsdienst"],
  [56, "KdoW-OrgL", "Rettungsdienst"],
  [73, "GRTW", "Rettungsdienst"],
  [74, "NAW", "Rettungsdienst"],
  [97, "ITW", "Rettungsdienst"],
  [157, "RTH Winde", "Rettungsdienst"],
  [58, "KTW Typ B", "Schnelleinsatzgruppe (SEG)"],
  [59, "ELW 1 (SEG)", "Schnelleinsatzgruppe (SEG)"],
  [60, "GW-San", "Schnelleinsatzgruppe (SEG)"],
  [63, "GW-Taucher", "Schnelleinsatzgruppe (SEG)"],
  [64, "GW-Wasserrettung", "Schnelleinsatzgruppe (SEG)"],
  [70, "MZB", "Schnelleinsatzgruppe (SEG)"],
  [91, "Rettungshundefahrzeug", "Schnelleinsatzgruppe (SEG)"],
  [127, "GW UAS", "Schnelleinsatzgruppe (SEG)"],
  [130, "GW-Bt", "Schnelleinsatzgruppe (SEG)"],
  [131, "Bt-Kombi", "Schnelleinsatzgruppe (SEG)"],
  [132, "FKH", "Schnelleinsatzgruppe (SEG)"],
  [133, "Bt LKW", "Schnelleinsatzgruppe (SEG)"],
  [171, "GW TeSi", "Schnelleinsatzgruppe (SEG)"],
  [172, "LKW Technik (Notstrom)", "Schnelleinsatzgruppe (SEG)"],
  [173, "MTW TeSi", "Schnelleinsatzgruppe (SEG)"],
  [174, "Anh TeSi", "Schnelleinsatzgruppe (SEG)"],
  [175, "NEA50", "Schnelleinsatzgruppe (SEG)"],
  [32, "FuStW", "Polizei"],
  [35, "leBefKw", "Polizei"],
  [50, "GruKw", "Polizei"],
  [51, "FüKW (Polizei)", "Polizei"],
  [52, "GefKw", "Polizei"],
  [61, "Polizeihubschrauber", "Polizei"],
  [72, "WaWe 10", "Polizei"],
  [79, "SEK - ZF", "Polizei"],
  [80, "SEK - MTF", "Polizei"],
  [81, "MEK - ZF", "Polizei"],
  [82, "MEK - MTF", "Polizei"],
  [94, "DHuFüKW", "Polizei"],
  [95, "Polizeimotorrad", "Polizei"],
  [96, "Außenlastbehälter (allgemein)", "Polizei"],
  [98, "Zivilstreifenwagen", "Polizei"],
  [103, "FuStW (DGL)", "Polizei"],
  [134, "Pferdetransporter klein", "Polizei"],
  [135, "Pferdetransporter groß", "Polizei"],
  [136, "Anh Pferdetransport", "Polizei"],
  [137, "Zugfahrzeug Pferdetransport", "Polizei"],
  [156, "Polizeihubschrauber mit verbauter Winde", "Polizei"],
  [165, "LauKw", "Polizei"],
  [184, "FuStW (AP)", "Polizei"],
  [39, "GKW", "THW"],
  [40, "MTW-TZ", "THW"],
  [41, "MzGW (FGr N)", "THW"],
  [42, "LKW K 9", "THW"],
  [43, "BRmG R", "THW"],
  [44, "Anh DLE", "THW"],
  [45, "MLW 5", "THW"],
  [65, "LKW 7 Lkr 19 tm", "THW"],
  [66, "Anh MzB", "THW"],
  [67, "Anh SchlB", "THW"],
  [68, "Anh MzAB", "THW"],
  [69, "Tauchkraftwagen", "THW"],
  [92, "Anh Hund", "THW"],
  [93, "MTW-O", "THW"],
  [100, "MLW 4", "THW"],
  [101, "Anh SwPu", "THW"],
  [102, "Anh 7", "THW"],
  [109, "MzGW SB", "THW"],
  [110, "NEA50", "THW"],
  [112, "NEA200", "THW"],
  [122, "LKW 7 Lbw (FGr E)", "THW"],
  [123, "LKW 7 Lbw (FGr WP)", "THW"],
  [124, "MTW-OV", "THW"],
  [125, "MTW-Tr UL", "THW"],
  [144, "FüKW (THW)", "THW"],
  [145, "FüKomKW", "THW"],
  [146, "Anh FüLa", "THW"],
  [147, "FmKW", "THW"],
  [148, "MTW-FGr K", "THW"],
  [176, "LKW 7 Lbw (FGr Log-V)", "THW"],
  [177, "MTW-FGr Log-V", "THW"],
  [178, "Anh 12 Lbw (FGr Log-V)", "THW"],
  [181, "MzGW (FGr BrB)", "THW"],
  [182, "Mobilkran", "THW"],
  [183, "Anh Plattform (FGr BrB)", "THW"],
  [149, "GW-Bergrettung (NEF)", "Bergrettung"],
  [150, "GW-Bergrettung", "Bergrettung"],
  [151, "ELW Bergrettung", "Bergrettung"],
  [152, "ATV", "Bergrettung"],
  [153, "Hundestaffel (Bergrettung)", "Bergrettung"],
  [154, "Schneefahrzeug", "Bergrettung"],
  [155, "Anh Höhenrettung (Bergrettung)", "Bergrettung"],
  [158, "GW-Höhenrettung (Bergrettung)", "Bergrettung"],
  [159, "Seenotrettungskreuzer", "Seenotrettung"],
  [160, "Seenotrettungsboot", "Seenotrettung"],
  [161, "Hubschrauber (Seenotrettung)", "Seenotrettung"]
];

const LSS_VEHICLE_GROUP_ORDER = ["Feuerwehr – Lösch- und Tanklöschfahrzeuge","Feuerwehr – Sonderfahrzeuge","Feuerwehr – Abrollbehälter / Anhänger","Rettungsdienst","Schnelleinsatzgruppe (SEG)","Polizei","THW","Bergrettung","Seenotrettung"];

// id -> offizieller Name
const LSS_TYPE_NAMES = Object.fromEntries(LSS_VEHICLE_TYPES.map(([id, name]) => [id, name]));
